var MemoryStore = function(successCallback, errorCallback) {

    /*this.findByName = function(searchKey, callback) {
        var employees = this.employees.filter(function(element) {
            var fullName = element.firstName + " " + element.lastName;
            return fullName.toLowerCase().indexOf(searchKey.toLowerCase()) > -1;
        });
        callLater(callback, employees);
    }*/

    this.findByName = function(searchKey, callback) {
        var items = this.items.filter(function(element) {
            var itemDetail = element.itemName + " " + element.itemType;
            return itemDetail.toLowerCase().indexOf(searchKey.toLowerCase()) > -1;
        });
        callLater(callback, items);
    }

    /*this.findById = function(id, callback) {
        var employees = this.employees;
        var employee = null;
        var l = employees.length;
        for (var i=0; i < l; i++) {
            if (employees[i].id === id) {
                employee = employees[i];
                break;
            }
        }
        callLater(callback, employee);
    }*/

    this.findById = function(id, callback) {
        var items = this.items;
        var item = null;
        var l = items.length;
        for (var i=0; i < l; i++) {
            if (items[i].id === id) {
                item = items[i];
                break;
            }
        }
        callLater(callback, item);
    }

    // Used to simulate async calls. This is done to provide a consistent interface with stores (like WebSqlStore)
    // that use async data access APIs
    var callLater = function(callback, data) {
        if (callback) {
            setTimeout(function() {
                callback(data);
            });
        }
    }

    this.employees = [
            {"id": 1, "firstName": "Ryan", "lastName": "Howard", "title":"Vice President, North East", "managerId": 0, "city":"New York, NY", "cellPhone":"212-999-8888", "officePhone":"212-999-8887", "email":"ryan@dundermifflin.com"},
            {"id": 2, "firstName": "Michael", "lastName": "Scott", "title":"Regional Manager", "managerId": 1, "city":"Scranton, PA", "cellPhone":"570-865-2536", "officePhone":"570-123-4567", "email":"michael@dundermifflin.com"},
            {"id": 3, "firstName": "Dwight", "lastName": "Schrute", "title":"Assistant Regional Manager", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-1158", "officePhone":"570-843-8963", "email":"dwight@dundermifflin.com"},
            {"id": 4, "firstName": "Jim", "lastName": "Halpert", "title":"Assistant Regional Manager", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-8989", "officePhone":"570-968-5741", "email":"dwight@dundermifflin.com"},
            {"id": 5, "firstName": "Pamela", "lastName": "Beesly", "title":"Receptionist", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-999-5555", "officePhone":"570-999-7474", "email":"pam@dundermifflin.com"},
            {"id": 6, "firstName": "Angela", "lastName": "Martin", "title":"Senior Accountant", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-555-9696", "officePhone":"570-999-3232", "email":"angela@dundermifflin.com"},
            {"id": 7, "firstName": "Kevin", "lastName": "Malone", "title":"Accountant", "managerId": 6, "city":"Scranton, PA", "cellPhone":"570-777-9696", "officePhone":"570-111-2525", "email":"kmalone@dundermifflin.com"},
            {"id": 8, "firstName": "Oscar", "lastName": "Martinez", "title":"Accountant", "managerId": 6, "city":"Scranton, PA", "cellPhone":"570-321-9999", "officePhone":"570-585-3333", "email":"oscar@dundermifflin.com"},
            {"id": 9, "firstName": "Creed", "lastName": "Bratton", "title":"Quality Assurance", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-222-6666", "officePhone":"570-333-8585", "email":"creed@dundermifflin.com"},
            {"id": 10, "firstName": "Andy", "lastName": "Bernard", "title":"Sales Director", "managerId": 4, "city":"Scranton, PA", "cellPhone":"570-555-0000", "officePhone":"570-646-9999", "email":"andy@dundermifflin.com"},
            {"id": 11, "firstName": "Phyllis", "lastName": "Lapin", "title":"Sales Representative", "managerId": 10, "city":"Scranton, PA", "cellPhone":"570-241-8585", "officePhone":"570-632-1919", "email":"phyllis@dundermifflin.com"},
            {"id": 12, "firstName": "Stanley", "lastName": "Hudson", "title":"Sales Representative", "managerId": 10, "city":"Scranton, PA", "cellPhone":"570-700-6464", "officePhone":"570-787-9393", "email":"shudson@dundermifflin.com"},
            {"id": 13, "firstName": "Meredith", "lastName": "Palmer", "title":"Supplier Relations", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-588-6567", "officePhone":"570-981-6167", "email":"meredith@dundermifflin.com"},
            {"id": 14, "firstName": "Kelly", "lastName": "Kapoor", "title":"Customer Service Rep.", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-123-9654", "officePhone":"570-125-3666", "email":"kelly@dundermifflin.com"},
            {"id": 15, "firstName": "Toby", "lastName": "Flenderson", "title":"Human Resources", "managerId": 1, "city":"Scranton, PA", "cellPhone":"570-485-8554", "officePhone":"570-699-5577", "email":"toby@dundermifflin.com"}
        ];

    this.items = [
    		{"Id":1,"itemName":"Antiperspirant / Deodorant","itemType":"Personal care","department":"Household"},
			{"Id":2,"itemName":"Bath soap / Hand soap","itemType":"Personal care","department":"Household"},
			{"Id":3,"itemName":"Condoms / Other b.c.","itemType":"Personal care","department":"Household"},
			{"Id":4,"itemName":"Cosmetics","itemType":"Personal care","department":"Household"},
			{"Id":5,"itemName":"Cotton swabs / Balls","itemType":"Personal care","department":"Household"},
			{"Id":6,"itemName":"Facial cleanser","itemType":"Personal care","department":"Household"},
			{"Id":7,"itemName":"Facial tissue","itemType":"Personal care","department":"Household"},
			{"Id":8,"itemName":"Feminine products","itemType":"Personal care","department":"Household"},
			{"Id":9,"itemName":"Floss","itemType":"Personal care","department":"Household"},
			{"Id":10,"itemName":"Hair gel / Spray","itemType":"Personal care","department":"Household"},
			{"Id":11,"itemName":"Lip balm","itemType":"Personal care","department":"Household"},
			{"Id":12,"itemName":"Moisturizing lotion","itemType":"Personal care","department":"Household"},
			{"Id":13,"itemName":"Mouthwash","itemType":"Personal care","department":"Household"},
			{"Id":14,"itemName":"Razors / Shaving cream","itemType":"Personal care","department":"Household"},
			{"Id":15,"itemName":"Shampoo / Conditioner","itemType":"Personal care","department":"Household"},
			{"Id":16,"itemName":"Sunblock","itemType":"Personal care","department":"Household"},
			{"Id":17,"itemName":"Toilet paper","itemType":"Personal care","department":"Household"},
			{"Id":18,"itemName":"Toothpaste","itemType":"Personal care","department":"Household"},
			{"Id":19,"itemName":"Vitamins / Supplements","itemType":"Personal care","department":"Household"},
			{"Id":20,"itemName":"Allergy","itemType":"Medicine","department":"Household"},
			{"Id":21,"itemName":"Antibiotic","itemType":"Medicine","department":"Household"},
			{"Id":22,"itemName":"Antidiarrheal","itemType":"Medicine","department":"Household"},
			{"Id":23,"itemName":"Aspirin","itemType":"Medicine","department":"Household"},
			{"Id":24,"itemName":"Antacid","itemType":"Medicine","department":"Household"},
			{"Id":25,"itemName":"Band-aids / Medical","itemType":"Medicine","department":"Household"},
			{"Id":26,"itemName":"Cold / Flu / Sinus","itemType":"Medicine","department":"Household"},
			{"Id":27,"itemName":"Pain reliever","itemType":"Medicine","department":"Household"},
			{"Id":28,"itemName":"Prescription pick-up","itemType":"Medicine","department":"Household"},
			{"Id":29,"itemName":"Aluminum foil","itemType":"Kitchen","department":"Household"},
			{"Id":30,"itemName":"Napkins","itemType":"Kitchen","department":"Household"},
			{"Id":31,"itemName":"Non-stick spray","itemType":"Kitchen","department":"Household"},
			{"Id":32,"itemName":"Paper towels","itemType":"Kitchen","department":"Household"},
			{"Id":33,"itemName":"Plastic wrap","itemType":"Kitchen","department":"Household"},
			{"Id":34,"itemName":"Sandwich / Freezer bags","itemType":"Kitchen","department":"Household"},
			{"Id":35,"itemName":"Wax paper","itemType":"Kitchen","department":"Household"},
			{"Id":36,"itemName":"Air freshener","itemType":"Cleaning products","department":"Household"},
			{"Id":37,"itemName":"Bathroom cleaner","itemType":"Cleaning products","department":"Household"},
			{"Id":38,"itemName":"Bleach / Detergent","itemType":"Cleaning products","department":"Household"},
			{"Id":39,"itemName":"Dish / Dishwasher soap","itemType":"Cleaning products","department":"Household"},
			{"Id":40,"itemName":"Garbage bags","itemType":"Cleaning products","department":"Household"},
			{"Id":41,"itemName":"Glass cleaner","itemType":"Cleaning products","department":"Household"},
			{"Id":42,"itemName":"Mop head / Vacuum bags","itemType":"Cleaning products","department":"Household"},
			{"Id":43,"itemName":"Sponges / Scrubbers","itemType":"Cleaning products","department":"Household"},
			{"Id":44,"itemName":"CDRs / DVDRs","itemType":"Office supplies","department":"Household"},
			{"Id":45,"itemName":"Notepad / Envelopes","itemType":"Office supplies","department":"Household"},
			{"Id":46,"itemName":"Glue / Tape","itemType":"Office supplies","department":"Household"},
			{"Id":47,"itemName":"Printer paper","itemType":"Office supplies","department":"Household"},
			{"Id":48,"itemName":"Pens / Pencils","itemType":"Office supplies","department":"Household"},
			{"Id":49,"itemName":"Postage stamps","itemType":"Office supplies","department":"Household"},
			{"Id":50,"itemName":"Arsenic","itemType":"Carcinogens","department":"Household"},
			{"Id":51,"itemName":"Asbestos","itemType":"Carcinogens","department":"Household"},
			{"Id":52,"itemName":"Cigarettes","itemType":"Carcinogens","department":"Household"},
			{"Id":53,"itemName":"Radionuclides","itemType":"Carcinogens","department":"Household"},
			{"Id":54,"itemName":"Vinyl chloride","itemType":"Carcinogens","department":"Household"},
			{"Id":55,"itemName":"Automotive","itemType":"Other stuff","department":"Household"},
			{"Id":56,"itemName":"Batteries","itemType":"Other stuff","department":"Household"},
			{"Id":57,"itemName":"Charcoal / Propane","itemType":"Other stuff","department":"Household"},
			{"Id":58,"itemName":"Flowers / Greeting card","itemType":"Other stuff","department":"Household"},
			{"Id":59,"itemName":"Insect repellent","itemType":"Other stuff","department":"Household"},
			{"Id":60,"itemName":"Light bulbs","itemType":"Other stuff","department":"Household"},
			{"Id":61,"itemName":"Newspaper / Magazine","itemType":"Other stuff","department":"Household"},
			{"Id":62,"itemName":"Random impulse buy","itemType":"Other stuff","department":"Household"},
			{"Id":63,"itemName":"Cat food / Treats","itemType":"Pets","department":"Foodstuff"},
			{"Id":64,"itemName":"Cat litter","itemType":"Pets","department":"Foodstuff"},
			{"Id":65,"itemName":"Dog food / Treats","itemType":"Pets","department":"Foodstuff"},
			{"Id":66,"itemName":"Flea treatment","itemType":"Pets","department":"Foodstuff"},
			{"Id":67,"itemName":"Pet shampoo","itemType":"Pets","department":"Foodstuff"},
			{"Id":68,"itemName":"Basil","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":69,"itemName":"Black pepper","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":70,"itemName":"Cilantro","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":71,"itemName":"Cinnamon","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":72,"itemName":"Garlic","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":73,"itemName":"Ginger","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":74,"itemName":"Mint","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":75,"itemName":"Oregano","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":76,"itemName":"Paprika","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":77,"itemName":"Parsley","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":78,"itemName":"Red pepper","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":79,"itemName":"Salt","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":80,"itemName":"Vanilla extract","itemType":"Spices & herbs","department":"Foodstuff"},
			{"Id":81,"itemName":"Beer","itemType":"Beverages","department":"Foodstuff"},
			{"Id":82,"itemName":"Club soda / Tonic","itemType":"Beverages","department":"Foodstuff"},
			{"Id":83,"itemName":"Champagne","itemType":"Beverages","department":"Foodstuff"},
			{"Id":84,"itemName":"Gin","itemType":"Beverages","department":"Foodstuff"},
			{"Id":85,"itemName":"Juice","itemType":"Beverages","department":"Foodstuff"},
			{"Id":86,"itemName":"Mixers","itemType":"Beverages","department":"Foodstuff"},
			{"Id":87,"itemName":"Red wine / White wine","itemType":"Beverages","department":"Foodstuff"},
			{"Id":88,"itemName":"Rum","itemType":"Beverages","department":"Foodstuff"},
			{"Id":89,"itemName":"Saké","itemType":"Beverages","department":"Foodstuff"},
			{"Id":90,"itemName":"Soda pop","itemType":"Beverages","department":"Foodstuff"},
			{"Id":91,"itemName":"Sports drink","itemType":"Beverages","department":"Foodstuff"},
			{"Id":92,"itemName":"Whiskey","itemType":"Beverages","department":"Foodstuff"},
			{"Id":93,"itemName":"Vodka","itemType":"Beverages","department":"Foodstuff"},
			{"Id":94,"itemName":"Breakfasts","itemType":"Frozen","department":"Foodstuff"},
			{"Id":95,"itemName":"Burritos","itemType":"Frozen","department":"Foodstuff"},
			{"Id":96,"itemName":"Fish sticks","itemType":"Frozen","department":"Foodstuff"},
			{"Id":97,"itemName":"Fries / Tater tots","itemType":"Frozen","department":"Foodstuff"},
			{"Id":98,"itemName":"Ice cream / Sorbet","itemType":"Frozen","department":"Foodstuff"},
			{"Id":99,"itemName":"Juice concentrate","itemType":"Frozen","department":"Foodstuff"},
			{"Id":100,"itemName":"Pizza","itemType":"Frozen","department":"Foodstuff"},
			{"Id":101,"itemName":"Pizza Rolls","itemType":"Frozen","department":"Foodstuff"},
			{"Id":102,"itemName":"Popsicles","itemType":"Frozen","department":"Foodstuff"},
			{"Id":103,"itemName":"TV dinners","itemType":"Frozen","department":"Foodstuff"},
			{"Id":104,"itemName":"Vegetables","itemType":"Frozen","department":"Foodstuff"},
			{"Id":105,"itemName":"Baby food","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":106,"itemName":"Diapers","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":107,"itemName":"Formula","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":108,"itemName":"Lotion","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":109,"itemName":"Baby wash","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":110,"itemName":"Wipes","itemType":"Baby stuff","department":"Foodstuff"},
			{"Id":111,"itemName":"Burger night","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":112,"itemName":"Chili night","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":113,"itemName":"Pizza night","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":114,"itemName":"Spaghetti night","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":115,"itemName":"Taco night","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":116,"itemName":"Take-out deli food","itemType":"Themed meals","department":"Foodstuff"},
			{"Id":117,"itemName":"Catfish","itemType":"Seafood","department":"Foodstuff"},
			{"Id":118,"itemName":"Crab","itemType":"Seafood","department":"Foodstuff"},
			{"Id":119,"itemName":"Lobster","itemType":"Seafood","department":"Foodstuff"},
			{"Id":120,"itemName":"Mussels","itemType":"Seafood","department":"Foodstuff"},
			{"Id":121,"itemName":"Oysters","itemType":"Seafood","department":"Foodstuff"},
			{"Id":122,"itemName":"Salmon","itemType":"Seafood","department":"Foodstuff"},
			{"Id":123,"itemName":"Shrimp","itemType":"Seafood","department":"Foodstuff"},
			{"Id":124,"itemName":"Tilapia","itemType":"Seafood","department":"Foodstuff"},
			{"Id":125,"itemName":"Tuna","itemType":"Seafood","department":"Foodstuff"},
			{"Id":126,"itemName":"Bagels","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":127,"itemName":"Chip dip","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":128,"itemName":"Eggs / Fake eggs","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":129,"itemName":"English muffins","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":130,"itemName":"Fruit juice","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":131,"itemName":"Hummus","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":132,"itemName":"Ready-bake breads","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":133,"itemName":"Tofu","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":134,"itemName":"Tortillas","itemType":"Refrigerated items","department":"Foodstuff"},
			{"Id":135,"itemName":"Applesauce","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":136,"itemName":"Baked beans","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":137,"itemName":"Broth","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":138,"itemName":"Fruit","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":139,"itemName":"Olives","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":140,"itemName":"Tinned meats","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":141,"itemName":"Tuna / Chicken","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":142,"itemName":"Soup / Chili","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":143,"itemName":"Tomatoes","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":144,"itemName":"Veggies","itemType":"Canned foods","department":"Foodstuff"},
			{"Id":145,"itemName":"Bacon / Sausage","itemType":"Meat","department":"Foodstuff"},
			{"Id":146,"itemName":"Beef","itemType":"Meat","department":"Foodstuff"},
			{"Id":147,"itemName":"Chicken","itemType":"Meat","department":"Foodstuff"},
			{"Id":148,"itemName":"Ground beef / Turkey","itemType":"Meat","department":"Foodstuff"},
			{"Id":149,"itemName":"Ham / Pork","itemType":"Meat","department":"Foodstuff"},
			{"Id":150,"itemName":"Hot dogs","itemType":"Meat","department":"Foodstuff"},
			{"Id":151,"itemName":"Lunchmeat","itemType":"Meat","department":"Foodstuff"},
			{"Id":152,"itemName":"Turkey","itemType":"Meat","department":"Foodstuff"},
			{"Id":153,"itemName":"Candy / Gum","itemType":"Snacks","department":"Foodstuff"},
			{"Id":154,"itemName":"Cookies","itemType":"Snacks","department":"Foodstuff"},
			{"Id":155,"itemName":"Crackers","itemType":"Snacks","department":"Foodstuff"},
			{"Id":156,"itemName":"Dried fruit","itemType":"Snacks","department":"Foodstuff"},
			{"Id":157,"itemName":"Granola bars / Mix","itemType":"Snacks","department":"Foodstuff"},
			{"Id":158,"itemName":"Nuts / Seeds","itemType":"Snacks","department":"Foodstuff"},
			{"Id":159,"itemName":"Oatmeal","itemType":"Snacks","department":"Foodstuff"},
			{"Id":160,"itemName":"Popcorn","itemType":"Snacks","department":"Foodstuff"},
			{"Id":161,"itemName":"Potato / Corn chips","itemType":"Snacks","department":"Foodstuff"},
			{"Id":162,"itemName":"Pretzels","itemType":"Snacks","department":"Foodstuff"},
			{"Id":163,"itemName":"Apples","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":164,"itemName":"Avocados","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":165,"itemName":"Bananas","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":166,"itemName":"Berries","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":167,"itemName":"Cherries","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":168,"itemName":"Grapefruit","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":169,"itemName":"Grapes","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":170,"itemName":"Kiwis","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":171,"itemName":"Lemons / Limes","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":172,"itemName":"Melon","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":173,"itemName":"Nectarines","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":174,"itemName":"Oranges","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":175,"itemName":"Peaches","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":176,"itemName":"Pears","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":177,"itemName":"Plums","itemType":"Fresh fruits","department":"Foodstuff"},
			{"Id":178,"itemName":"Bouillon cubes","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":179,"itemName":"Cereal","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":180,"itemName":"Coffee / Filters","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":181,"itemName":"Instant potatoes","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":182,"itemName":"Lemon / Lime juice","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":183,"itemName":"Mac & cheese","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":184,"itemName":"Olive oil","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":185,"itemName":"Packaged meals","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":186,"itemName":"Pancake / Waffle mix","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":187,"itemName":"Pasta","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":188,"itemName":"Peanut butter","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":189,"itemName":"Pickles","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":190,"itemName":"Rice","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":191,"itemName":"Tea","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":192,"itemName":"Vegetable oil","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":193,"itemName":"Vinegar","itemType":"Various groceries","department":"Foodstuff"},
			{"Id":194,"itemName":"Bleu cheese","itemType":"Cheese","department":"Foodstuff"},
			{"Id":195,"itemName":"Cheddar","itemType":"Cheese","department":"Foodstuff"},
			{"Id":196,"itemName":"Cottage cheese","itemType":"Cheese","department":"Foodstuff"},
			{"Id":197,"itemName":"Cream cheese","itemType":"Cheese","department":"Foodstuff"},
			{"Id":198,"itemName":"Feta","itemType":"Cheese","department":"Foodstuff"},
			{"Id":199,"itemName":"Goat cheese","itemType":"Cheese","department":"Foodstuff"},
			{"Id":200,"itemName":"Mozzarella","itemType":"Cheese","department":"Foodstuff"},
			{"Id":201,"itemName":"Parmesan","itemType":"Cheese","department":"Foodstuff"},
			{"Id":202,"itemName":"Provolone","itemType":"Cheese","department":"Foodstuff"},
			{"Id":203,"itemName":"Ricotta","itemType":"Cheese","department":"Foodstuff"},
			{"Id":204,"itemName":"Sandwich slices","itemType":"Cheese","department":"Foodstuff"},
			{"Id":205,"itemName":"Swiss","itemType":"Cheese","department":"Foodstuff"},
			{"Id":206,"itemName":"Baking powder / Soda","itemType":"Baking","department":"Foodstuff"},
			{"Id":207,"itemName":"Bread crumbs","itemType":"Baking","department":"Foodstuff"},
			{"Id":208,"itemName":"Cake / Brownie mix","itemType":"Baking","department":"Foodstuff"},
			{"Id":209,"itemName":"Cake icing / Decorations","itemType":"Baking","department":"Foodstuff"},
			{"Id":210,"itemName":"Chocolate chips / Cocoa","itemType":"Baking","department":"Foodstuff"},
			{"Id":211,"itemName":"Flour","itemType":"Baking","department":"Foodstuff"},
			{"Id":212,"itemName":"Shortening","itemType":"Baking","department":"Foodstuff"},
			{"Id":213,"itemName":"Sugar","itemType":"Baking","department":"Foodstuff"},
			{"Id":214,"itemName":"Sugar substitute","itemType":"Baking","department":"Foodstuff"},
			{"Id":215,"itemName":"Yeast","itemType":"Baking","department":"Foodstuff"},
			{"Id":216,"itemName":"Asparagus","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":217,"itemName":"Broccoli","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":218,"itemName":"Carrots","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":219,"itemName":"Cauliflower","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":220,"itemName":"Celery","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":221,"itemName":"Corn","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":222,"itemName":"Cucumbers","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":223,"itemName":"Lettuce / Greens","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":224,"itemName":"Mushrooms","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":225,"itemName":"Onions","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":226,"itemName":"Peppers","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":227,"itemName":"Potatoes","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":228,"itemName":"Spinach","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":229,"itemName":"Squash","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":230,"itemName":"Zucchini","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":231,"itemName":"Tomatoes*","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"Id":232,"itemName":"BBQ sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":233,"itemName":"Gravy","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":234,"itemName":"Honey","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":235,"itemName":"Hot sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":236,"itemName":"Jam / Jelly / Preserves","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":237,"itemName":"Ketchup / Mustard","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":238,"itemName":"Mayonnaise","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":239,"itemName":"Pasta sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":240,"itemName":"Relish","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":241,"itemName":"Salad dressing","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":242,"itemName":"Salsa","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":243,"itemName":"Soy sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":244,"itemName":"Steak sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":245,"itemName":"Syrup","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":246,"itemName":"Worcestershire sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"Id":247,"itemName":"Butter / Margarine","itemType":"Dairy","department":"Foodstuff"},
			{"Id":248,"itemName":"Cottage cheese","itemType":"Dairy","department":"Foodstuff"},
			{"Id":249,"itemName":"Half & half","itemType":"Dairy","department":"Foodstuff"},
			{"Id":250,"itemName":"Milk","itemType":"Dairy","department":"Foodstuff"},
			{"Id":251,"itemName":"Sour cream","itemType":"Dairy","department":"Foodstuff"},
			{"Id":252,"itemName":"Whipped cream","itemType":"Dairy","department":"Foodstuff"},
			{"Id":253,"itemName":"Yogurt","itemType":"Dairy","department":"Foodstuff"},
			{"Id":254,"itemName":"Bagels / Croissants","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":255,"itemName":"Buns / Rolls","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":256,"itemName":"Cake / Cookies","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":257,"itemName":"Donuts / Pastries","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":258,"itemName":"Fresh bread","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":259,"itemName":"Pie! Pie! Pie!","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":260,"itemName":"Pita bread","itemType":"Baked goods","department":"Foodstuff"},
			{"Id":261,"itemName":"Sliced bread","itemType":"Baked goods","department":"Foodstuff"}
		];

    callLater(successCallback);

}