var MemoryStore = function(successCallback, errorCallback) {

    /*this.findByName = function(searchKey, callback) {
        var employees = this.employees.filter(function(element) {
            var fullName = element.firstName + " " + element.lastName;
            return fullName.toLowerCase().indexOf(searchKey.toLowerCase()) > -1;
        });
        callLater(callback, employees);
    }*/

    this.findByName = function(searchKey, callback) {
        var items = this.items.filter(function(element) {
            var itemDetail = element.itemName + " " + element.itemType;
            return itemDetail.toLowerCase().indexOf(searchKey.toLowerCase()) > -1;
        });
        callLater(callback, items);
    }

    /*this.findById = function(id, callback) {
        var employees = this.employees;
        var employee = null;
        var l = employees.length;
        for (var i=0; i < l; i++) {
            if (employees[i].id === id) {
                employee = employees[i];
                break;
            }
        }
        callLater(callback, employee);
    }*/

    this.findById = function(id, callback) {
        var items = this.items;
        var item = null;
        var l = items.length;
        for (var i=0; i < l; i++) {
            if (items[i].id === id) {
                item = items[i];
                break;
            }
        }
        callLater(callback, item);
    }

    // Used to simulate async calls. This is done to provide a consistent interface with stores (like WebSqlStore)
    // that use async data access APIs
    var callLater = function(callback, data) {
        if (callback) {
            setTimeout(function() {
                callback(data);
            });
        }
    }

    this.employees = [
            {"id": 1, "firstName": "Ryan", "lastName": "Howard", "title":"Vice President, North East", "managerId": 0, "city":"New York, NY", "cellPhone":"212-999-8888", "officePhone":"212-999-8887", "email":"ryan@dundermifflin.com"},
            {"id": 2, "firstName": "Michael", "lastName": "Scott", "title":"Regional Manager", "managerId": 1, "city":"Scranton, PA", "cellPhone":"570-865-2536", "officePhone":"570-123-4567", "email":"michael@dundermifflin.com"},
            {"id": 3, "firstName": "Dwight", "lastName": "Schrute", "title":"Assistant Regional Manager", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-1158", "officePhone":"570-843-8963", "email":"dwight@dundermifflin.com"},
            {"id": 4, "firstName": "Jim", "lastName": "Halpert", "title":"Assistant Regional Manager", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-865-8989", "officePhone":"570-968-5741", "email":"dwight@dundermifflin.com"},
            {"id": 5, "firstName": "Pamela", "lastName": "Beesly", "title":"Receptionist", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-999-5555", "officePhone":"570-999-7474", "email":"pam@dundermifflin.com"},
            {"id": 6, "firstName": "Angela", "lastName": "Martin", "title":"Senior Accountant", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-555-9696", "officePhone":"570-999-3232", "email":"angela@dundermifflin.com"},
            {"id": 7, "firstName": "Kevin", "lastName": "Malone", "title":"Accountant", "managerId": 6, "city":"Scranton, PA", "cellPhone":"570-777-9696", "officePhone":"570-111-2525", "email":"kmalone@dundermifflin.com"},
            {"id": 8, "firstName": "Oscar", "lastName": "Martinez", "title":"Accountant", "managerId": 6, "city":"Scranton, PA", "cellPhone":"570-321-9999", "officePhone":"570-585-3333", "email":"oscar@dundermifflin.com"},
            {"id": 9, "firstName": "Creed", "lastName": "Bratton", "title":"Quality Assurance", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-222-6666", "officePhone":"570-333-8585", "email":"creed@dundermifflin.com"},
            {"id": 10, "firstName": "Andy", "lastName": "Bernard", "title":"Sales Director", "managerId": 4, "city":"Scranton, PA", "cellPhone":"570-555-0000", "officePhone":"570-646-9999", "email":"andy@dundermifflin.com"},
            {"id": 11, "firstName": "Phyllis", "lastName": "Lapin", "title":"Sales Representative", "managerId": 10, "city":"Scranton, PA", "cellPhone":"570-241-8585", "officePhone":"570-632-1919", "email":"phyllis@dundermifflin.com"},
            {"id": 12, "firstName": "Stanley", "lastName": "Hudson", "title":"Sales Representative", "managerId": 10, "city":"Scranton, PA", "cellPhone":"570-700-6464", "officePhone":"570-787-9393", "email":"shudson@dundermifflin.com"},
            {"id": 13, "firstName": "Meredith", "lastName": "Palmer", "title":"Supplier Relations", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-588-6567", "officePhone":"570-981-6167", "email":"meredith@dundermifflin.com"},
            {"id": 14, "firstName": "Kelly", "lastName": "Kapoor", "title":"Customer Service Rep.", "managerId": 2, "city":"Scranton, PA", "cellPhone":"570-123-9654", "officePhone":"570-125-3666", "email":"kelly@dundermifflin.com"},
            {"id": 15, "firstName": "Toby", "lastName": "Flenderson", "title":"Human Resources", "managerId": 1, "city":"Scranton, PA", "cellPhone":"570-485-8554", "officePhone":"570-699-5577", "email":"toby@dundermifflin.com"}
        ];

    this.items = [
    		{"id":1,"itemName":"Antiperspirant / Deodorant","itemType":"Personal care","department":"Household"},
			{"id":2,"itemName":"Bath soap / Hand soap","itemType":"Personal care","department":"Household"},
			{"id":3,"itemName":"Condoms / Other b.c.","itemType":"Personal care","department":"Household"},
			{"id":4,"itemName":"Cosmetics","itemType":"Personal care","department":"Household"},
			{"id":5,"itemName":"Cotton swabs / Balls","itemType":"Personal care","department":"Household"},
			{"id":6,"itemName":"Facial cleanser","itemType":"Personal care","department":"Household"},
			{"id":7,"itemName":"Facial tissue","itemType":"Personal care","department":"Household"},
			{"id":8,"itemName":"Feminine products","itemType":"Personal care","department":"Household"},
			{"id":9,"itemName":"Floss","itemType":"Personal care","department":"Household"},
			{"id":10,"itemName":"Hair gel / Spray","itemType":"Personal care","department":"Household"},
			{"id":11,"itemName":"Lip balm","itemType":"Personal care","department":"Household"},
			{"id":12,"itemName":"Moisturizing lotion","itemType":"Personal care","department":"Household"},
			{"id":13,"itemName":"Mouthwash","itemType":"Personal care","department":"Household"},
			{"id":14,"itemName":"Razors / Shaving cream","itemType":"Personal care","department":"Household"},
			{"id":15,"itemName":"Shampoo / Conditioner","itemType":"Personal care","department":"Household"},
			{"id":16,"itemName":"Sunblock","itemType":"Personal care","department":"Household"},
			{"id":17,"itemName":"Toilet paper","itemType":"Personal care","department":"Household"},
			{"id":18,"itemName":"Toothpaste","itemType":"Personal care","department":"Household"},
			{"id":19,"itemName":"Vitamins / Supplements","itemType":"Personal care","department":"Household"},
			{"id":20,"itemName":"Allergy","itemType":"Medicine","department":"Household"},
			{"id":21,"itemName":"Antibiotic","itemType":"Medicine","department":"Household"},
			{"id":22,"itemName":"Antidiarrheal","itemType":"Medicine","department":"Household"},
			{"id":23,"itemName":"Aspirin","itemType":"Medicine","department":"Household"},
			{"id":24,"itemName":"Antacid","itemType":"Medicine","department":"Household"},
			{"id":25,"itemName":"Band-aids / Medical","itemType":"Medicine","department":"Household"},
			{"id":26,"itemName":"Cold / Flu / Sinus","itemType":"Medicine","department":"Household"},
			{"id":27,"itemName":"Pain reliever","itemType":"Medicine","department":"Household"},
			{"id":28,"itemName":"Prescription pick-up","itemType":"Medicine","department":"Household"},
			{"id":29,"itemName":"Aluminum foil","itemType":"Kitchen","department":"Household"},
			{"id":30,"itemName":"Napkins","itemType":"Kitchen","department":"Household"},
			{"id":31,"itemName":"Non-stick spray","itemType":"Kitchen","department":"Household"},
			{"id":32,"itemName":"Paper towels","itemType":"Kitchen","department":"Household"},
			{"id":33,"itemName":"Plastic wrap","itemType":"Kitchen","department":"Household"},
			{"id":34,"itemName":"Sandwich / Freezer bags","itemType":"Kitchen","department":"Household"},
			{"id":35,"itemName":"Wax paper","itemType":"Kitchen","department":"Household"},
			{"id":36,"itemName":"Air freshener","itemType":"Cleaning products","department":"Household"},
			{"id":37,"itemName":"Bathroom cleaner","itemType":"Cleaning products","department":"Household"},
			{"id":38,"itemName":"Bleach / Detergent","itemType":"Cleaning products","department":"Household"},
			{"id":39,"itemName":"Dish / Dishwasher soap","itemType":"Cleaning products","department":"Household"},
			{"id":40,"itemName":"Garbage bags","itemType":"Cleaning products","department":"Household"},
			{"id":41,"itemName":"Glass cleaner","itemType":"Cleaning products","department":"Household"},
			{"id":42,"itemName":"Mop head / Vacuum bags","itemType":"Cleaning products","department":"Household"},
			{"id":43,"itemName":"Sponges / Scrubbers","itemType":"Cleaning products","department":"Household"},
			{"id":44,"itemName":"CDRs / DVDRs","itemType":"Office supplies","department":"Household"},
			{"id":45,"itemName":"Notepad / Envelopes","itemType":"Office supplies","department":"Household"},
			{"id":46,"itemName":"Glue / Tape","itemType":"Office supplies","department":"Household"},
			{"id":47,"itemName":"Printer paper","itemType":"Office supplies","department":"Household"},
			{"id":48,"itemName":"Pens / Pencils","itemType":"Office supplies","department":"Household"},
			{"id":49,"itemName":"Postage stamps","itemType":"Office supplies","department":"Household"},
			{"id":50,"itemName":"Arsenic","itemType":"Carcinogens","department":"Household"},
			{"id":51,"itemName":"Asbestos","itemType":"Carcinogens","department":"Household"},
			{"id":52,"itemName":"Cigarettes","itemType":"Carcinogens","department":"Household"},
			{"id":53,"itemName":"Radionuclides","itemType":"Carcinogens","department":"Household"},
			{"id":54,"itemName":"Vinyl chloride","itemType":"Carcinogens","department":"Household"},
			{"id":55,"itemName":"Automotive","itemType":"Other stuff","department":"Household"},
			{"id":56,"itemName":"Batteries","itemType":"Other stuff","department":"Household"},
			{"id":57,"itemName":"Charcoal / Propane","itemType":"Other stuff","department":"Household"},
			{"id":58,"itemName":"Flowers / Greeting card","itemType":"Other stuff","department":"Household"},
			{"id":59,"itemName":"Insect repellent","itemType":"Other stuff","department":"Household"},
			{"id":60,"itemName":"Light bulbs","itemType":"Other stuff","department":"Household"},
			{"id":61,"itemName":"Newspaper / Magazine","itemType":"Other stuff","department":"Household"},
			{"id":62,"itemName":"Random impulse buy","itemType":"Other stuff","department":"Household"},
			{"id":63,"itemName":"Cat food / Treats","itemType":"Pets","department":"Foodstuff"},
			{"id":64,"itemName":"Cat litter","itemType":"Pets","department":"Foodstuff"},
			{"id":65,"itemName":"Dog food / Treats","itemType":"Pets","department":"Foodstuff"},
			{"id":66,"itemName":"Flea treatment","itemType":"Pets","department":"Foodstuff"},
			{"id":67,"itemName":"Pet shampoo","itemType":"Pets","department":"Foodstuff"},
			{"id":68,"itemName":"Basil","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":69,"itemName":"Black pepper","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":70,"itemName":"Cilantro","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":71,"itemName":"Cinnamon","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":72,"itemName":"Garlic","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":73,"itemName":"Ginger","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":74,"itemName":"Mint","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":75,"itemName":"Oregano","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":76,"itemName":"Paprika","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":77,"itemName":"Parsley","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":78,"itemName":"Red pepper","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":79,"itemName":"Salt","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":80,"itemName":"Vanilla extract","itemType":"Spices & herbs","department":"Foodstuff"},
			{"id":81,"itemName":"Beer","itemType":"Beverages","department":"Foodstuff"},
			{"id":82,"itemName":"Club soda / Tonic","itemType":"Beverages","department":"Foodstuff"},
			{"id":83,"itemName":"Champagne","itemType":"Beverages","department":"Foodstuff"},
			{"id":84,"itemName":"Gin","itemType":"Beverages","department":"Foodstuff"},
			{"id":85,"itemName":"Juice","itemType":"Beverages","department":"Foodstuff"},
			{"id":86,"itemName":"Mixers","itemType":"Beverages","department":"Foodstuff"},
			{"id":87,"itemName":"Red wine / White wine","itemType":"Beverages","department":"Foodstuff"},
			{"id":88,"itemName":"Rum","itemType":"Beverages","department":"Foodstuff"},
			{"id":89,"itemName":"Saké","itemType":"Beverages","department":"Foodstuff"},
			{"id":90,"itemName":"Soda pop","itemType":"Beverages","department":"Foodstuff"},
			{"id":91,"itemName":"Sports drink","itemType":"Beverages","department":"Foodstuff"},
			{"id":92,"itemName":"Whiskey","itemType":"Beverages","department":"Foodstuff"},
			{"id":93,"itemName":"Vodka","itemType":"Beverages","department":"Foodstuff"},
			{"id":94,"itemName":"Breakfasts","itemType":"Frozen","department":"Foodstuff"},
			{"id":95,"itemName":"Burritos","itemType":"Frozen","department":"Foodstuff"},
			{"id":96,"itemName":"Fish sticks","itemType":"Frozen","department":"Foodstuff"},
			{"id":97,"itemName":"Fries / Tater tots","itemType":"Frozen","department":"Foodstuff"},
			{"id":98,"itemName":"Ice cream / Sorbet","itemType":"Frozen","department":"Foodstuff"},
			{"id":99,"itemName":"Juice concentrate","itemType":"Frozen","department":"Foodstuff"},
			{"id":100,"itemName":"Pizza","itemType":"Frozen","department":"Foodstuff"},
			{"id":101,"itemName":"Pizza Rolls","itemType":"Frozen","department":"Foodstuff"},
			{"id":102,"itemName":"Popsicles","itemType":"Frozen","department":"Foodstuff"},
			{"id":103,"itemName":"TV dinners","itemType":"Frozen","department":"Foodstuff"},
			{"id":104,"itemName":"Vegetables","itemType":"Frozen","department":"Foodstuff"},
			{"id":105,"itemName":"Baby food","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":106,"itemName":"Diapers","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":107,"itemName":"Formula","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":108,"itemName":"Lotion","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":109,"itemName":"Baby wash","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":110,"itemName":"Wipes","itemType":"Baby stuff","department":"Foodstuff"},
			{"id":111,"itemName":"Burger night","itemType":"Themed meals","department":"Foodstuff"},
			{"id":112,"itemName":"Chili night","itemType":"Themed meals","department":"Foodstuff"},
			{"id":113,"itemName":"Pizza night","itemType":"Themed meals","department":"Foodstuff"},
			{"id":114,"itemName":"Spaghetti night","itemType":"Themed meals","department":"Foodstuff"},
			{"id":115,"itemName":"Taco night","itemType":"Themed meals","department":"Foodstuff"},
			{"id":116,"itemName":"Take-out deli food","itemType":"Themed meals","department":"Foodstuff"},
			{"id":117,"itemName":"Catfish","itemType":"Seafood","department":"Foodstuff"},
			{"id":118,"itemName":"Crab","itemType":"Seafood","department":"Foodstuff"},
			{"id":119,"itemName":"Lobster","itemType":"Seafood","department":"Foodstuff"},
			{"id":120,"itemName":"Mussels","itemType":"Seafood","department":"Foodstuff"},
			{"id":121,"itemName":"Oysters","itemType":"Seafood","department":"Foodstuff"},
			{"id":122,"itemName":"Salmon","itemType":"Seafood","department":"Foodstuff"},
			{"id":123,"itemName":"Shrimp","itemType":"Seafood","department":"Foodstuff"},
			{"id":124,"itemName":"Tilapia","itemType":"Seafood","department":"Foodstuff"},
			{"id":125,"itemName":"Tuna","itemType":"Seafood","department":"Foodstuff"},
			{"id":126,"itemName":"Bagels","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":127,"itemName":"Chip dip","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":128,"itemName":"Eggs / Fake eggs","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":129,"itemName":"English muffins","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":130,"itemName":"Fruit juice","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":131,"itemName":"Hummus","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":132,"itemName":"Ready-bake breads","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":133,"itemName":"Tofu","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":134,"itemName":"Tortillas","itemType":"Refrigerated items","department":"Foodstuff"},
			{"id":135,"itemName":"Applesauce","itemType":"Canned foods","department":"Foodstuff"},
			{"id":136,"itemName":"Baked beans","itemType":"Canned foods","department":"Foodstuff"},
			{"id":137,"itemName":"Broth","itemType":"Canned foods","department":"Foodstuff"},
			{"id":138,"itemName":"Fruit","itemType":"Canned foods","department":"Foodstuff"},
			{"id":139,"itemName":"Olives","itemType":"Canned foods","department":"Foodstuff"},
			{"id":140,"itemName":"Tinned meats","itemType":"Canned foods","department":"Foodstuff"},
			{"id":141,"itemName":"Tuna / Chicken","itemType":"Canned foods","department":"Foodstuff"},
			{"id":142,"itemName":"Soup / Chili","itemType":"Canned foods","department":"Foodstuff"},
			{"id":143,"itemName":"Tomatoes","itemType":"Canned foods","department":"Foodstuff"},
			{"id":144,"itemName":"Veggies","itemType":"Canned foods","department":"Foodstuff"},
			{"id":145,"itemName":"Bacon / Sausage","itemType":"Meat","department":"Foodstuff"},
			{"id":146,"itemName":"Beef","itemType":"Meat","department":"Foodstuff"},
			{"id":147,"itemName":"Chicken","itemType":"Meat","department":"Foodstuff"},
			{"id":148,"itemName":"Ground beef / Turkey","itemType":"Meat","department":"Foodstuff"},
			{"id":149,"itemName":"Ham / Pork","itemType":"Meat","department":"Foodstuff"},
			{"id":150,"itemName":"Hot dogs","itemType":"Meat","department":"Foodstuff"},
			{"id":151,"itemName":"Lunchmeat","itemType":"Meat","department":"Foodstuff"},
			{"id":152,"itemName":"Turkey","itemType":"Meat","department":"Foodstuff"},
			{"id":153,"itemName":"Candy / Gum","itemType":"Snacks","department":"Foodstuff"},
			{"id":154,"itemName":"Cookies","itemType":"Snacks","department":"Foodstuff"},
			{"id":155,"itemName":"Crackers","itemType":"Snacks","department":"Foodstuff"},
			{"id":156,"itemName":"Dried fruit","itemType":"Snacks","department":"Foodstuff"},
			{"id":157,"itemName":"Granola bars / Mix","itemType":"Snacks","department":"Foodstuff"},
			{"id":158,"itemName":"Nuts / Seeds","itemType":"Snacks","department":"Foodstuff"},
			{"id":159,"itemName":"Oatmeal","itemType":"Snacks","department":"Foodstuff"},
			{"id":160,"itemName":"Popcorn","itemType":"Snacks","department":"Foodstuff"},
			{"id":161,"itemName":"Potato / Corn chips","itemType":"Snacks","department":"Foodstuff"},
			{"id":162,"itemName":"Pretzels","itemType":"Snacks","department":"Foodstuff"},
			{"id":163,"itemName":"Apples","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":164,"itemName":"Avocados","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":165,"itemName":"Bananas","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":166,"itemName":"Berries","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":167,"itemName":"Cherries","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":168,"itemName":"Grapefruit","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":169,"itemName":"Grapes","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":170,"itemName":"Kiwis","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":171,"itemName":"Lemons / Limes","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":172,"itemName":"Melon","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":173,"itemName":"Nectarines","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":174,"itemName":"Oranges","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":175,"itemName":"Peaches","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":176,"itemName":"Pears","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":177,"itemName":"Plums","itemType":"Fresh fruits","department":"Foodstuff"},
			{"id":178,"itemName":"Bouillon cubes","itemType":"Various groceries","department":"Foodstuff"},
			{"id":179,"itemName":"Cereal","itemType":"Various groceries","department":"Foodstuff"},
			{"id":180,"itemName":"Coffee / Filters","itemType":"Various groceries","department":"Foodstuff"},
			{"id":181,"itemName":"Instant potatoes","itemType":"Various groceries","department":"Foodstuff"},
			{"id":182,"itemName":"Lemon / Lime juice","itemType":"Various groceries","department":"Foodstuff"},
			{"id":183,"itemName":"Mac & cheese","itemType":"Various groceries","department":"Foodstuff"},
			{"id":184,"itemName":"Olive oil","itemType":"Various groceries","department":"Foodstuff"},
			{"id":185,"itemName":"Packaged meals","itemType":"Various groceries","department":"Foodstuff"},
			{"id":186,"itemName":"Pancake / Waffle mix","itemType":"Various groceries","department":"Foodstuff"},
			{"id":187,"itemName":"Pasta","itemType":"Various groceries","department":"Foodstuff"},
			{"id":188,"itemName":"Peanut butter","itemType":"Various groceries","department":"Foodstuff"},
			{"id":189,"itemName":"Pickles","itemType":"Various groceries","department":"Foodstuff"},
			{"id":190,"itemName":"Rice","itemType":"Various groceries","department":"Foodstuff"},
			{"id":191,"itemName":"Tea","itemType":"Various groceries","department":"Foodstuff"},
			{"id":192,"itemName":"Vegetable oil","itemType":"Various groceries","department":"Foodstuff"},
			{"id":193,"itemName":"Vinegar","itemType":"Various groceries","department":"Foodstuff"},
			{"id":194,"itemName":"Bleu cheese","itemType":"Cheese","department":"Foodstuff"},
			{"id":195,"itemName":"Cheddar","itemType":"Cheese","department":"Foodstuff"},
			{"id":196,"itemName":"Cottage cheese","itemType":"Cheese","department":"Foodstuff"},
			{"id":197,"itemName":"Cream cheese","itemType":"Cheese","department":"Foodstuff"},
			{"id":198,"itemName":"Feta","itemType":"Cheese","department":"Foodstuff"},
			{"id":199,"itemName":"Goat cheese","itemType":"Cheese","department":"Foodstuff"},
			{"id":200,"itemName":"Mozzarella","itemType":"Cheese","department":"Foodstuff"},
			{"id":201,"itemName":"Parmesan","itemType":"Cheese","department":"Foodstuff"},
			{"id":202,"itemName":"Provolone","itemType":"Cheese","department":"Foodstuff"},
			{"id":203,"itemName":"Ricotta","itemType":"Cheese","department":"Foodstuff"},
			{"id":204,"itemName":"Sandwich slices","itemType":"Cheese","department":"Foodstuff"},
			{"id":205,"itemName":"Swiss","itemType":"Cheese","department":"Foodstuff"},
			{"id":206,"itemName":"Baking powder / Soda","itemType":"Baking","department":"Foodstuff"},
			{"id":207,"itemName":"Bread crumbs","itemType":"Baking","department":"Foodstuff"},
			{"id":208,"itemName":"Cake / Brownie mix","itemType":"Baking","department":"Foodstuff"},
			{"id":209,"itemName":"Cake icing / Decorations","itemType":"Baking","department":"Foodstuff"},
			{"id":210,"itemName":"Chocolate chips / Cocoa","itemType":"Baking","department":"Foodstuff"},
			{"id":211,"itemName":"Flour","itemType":"Baking","department":"Foodstuff"},
			{"id":212,"itemName":"Shortening","itemType":"Baking","department":"Foodstuff"},
			{"id":213,"itemName":"Sugar","itemType":"Baking","department":"Foodstuff"},
			{"id":214,"itemName":"Sugar substitute","itemType":"Baking","department":"Foodstuff"},
			{"id":215,"itemName":"Yeast","itemType":"Baking","department":"Foodstuff"},
			{"id":216,"itemName":"Asparagus","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":217,"itemName":"Broccoli","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":218,"itemName":"Carrots","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":219,"itemName":"Cauliflower","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":220,"itemName":"Celery","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":221,"itemName":"Corn","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":222,"itemName":"Cucumbers","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":223,"itemName":"Lettuce / Greens","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":224,"itemName":"Mushrooms","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":225,"itemName":"Onions","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":226,"itemName":"Peppers","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":227,"itemName":"Potatoes","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":228,"itemName":"Spinach","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":229,"itemName":"Squash","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":230,"itemName":"Zucchini","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":231,"itemName":"Tomatoes*","itemType":"Fresh vegetables","department":"Foodstuff"},
			{"id":232,"itemName":"BBQ sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":233,"itemName":"Gravy","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":234,"itemName":"Honey","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":235,"itemName":"Hot sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":236,"itemName":"Jam / Jelly / Preserves","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":237,"itemName":"Ketchup / Mustard","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":238,"itemName":"Mayonnaise","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":239,"itemName":"Pasta sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":240,"itemName":"Relish","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":241,"itemName":"Salad dressing","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":242,"itemName":"Salsa","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":243,"itemName":"Soy sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":244,"itemName":"Steak sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":245,"itemName":"Syrup","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":246,"itemName":"Worcestershire sauce","itemType":"Condiments / Sauces","department":"Foodstuff"},
			{"id":247,"itemName":"Butter / Margarine","itemType":"Dairy","department":"Foodstuff"},
			{"id":248,"itemName":"Cottage cheese","itemType":"Dairy","department":"Foodstuff"},
			{"id":249,"itemName":"Half & half","itemType":"Dairy","department":"Foodstuff"},
			{"id":250,"itemName":"Milk","itemType":"Dairy","department":"Foodstuff"},
			{"id":251,"itemName":"Sour cream","itemType":"Dairy","department":"Foodstuff"},
			{"id":252,"itemName":"Whipped cream","itemType":"Dairy","department":"Foodstuff"},
			{"id":253,"itemName":"Yogurt","itemType":"Dairy","department":"Foodstuff"},
			{"id":254,"itemName":"Bagels / Croissants","itemType":"Baked goods","department":"Foodstuff"},
			{"id":255,"itemName":"Buns / Rolls","itemType":"Baked goods","department":"Foodstuff"},
			{"id":256,"itemName":"Cake / Cookies","itemType":"Baked goods","department":"Foodstuff"},
			{"id":257,"itemName":"Donuts / Pastries","itemType":"Baked goods","department":"Foodstuff"},
			{"id":258,"itemName":"Fresh bread","itemType":"Baked goods","department":"Foodstuff"},
			{"id":259,"itemName":"Pie! Pie! Pie!","itemType":"Baked goods","department":"Foodstuff"},
			{"id":260,"itemName":"Pita bread","itemType":"Baked goods","department":"Foodstuff"},
			{"id":261,"itemName":"Sliced bread","itemType":"Baked goods","department":"Foodstuff"}
		];

    callLater(successCallback);

}